import { Tenant } from '@prisma/client';

import { Employee } from '@prisma/client';

// Database model types (generated by Prisma)
export type {
  Tenant,
  User,
  Employee,
  CustomField,
  AuditLog,
  Session,
  AnalyticsEvent,
} from '@prisma/client';

// API Request/Response types
export interface CreateEmployeeRequest {
  firstName: string;
  lastName: string;
  title?: string;
  department?: string;
  email: string;
  phone?: string;
  extension?: string;
  officeLocation?: string;
  managerId?: string;
  bio?: string;
  skills?: string[];
  customFields?: Record<string, any>;
}

export interface UpdateEmployeeRequest {
  firstName?: string;
  lastName?: string;
  title?: string;
  department?: string;
  email?: string;
  phone?: string;
  extension?: string;
  officeLocation?: string;
  managerId?: string;
  bio?: string;
  skills?: string[];
  customFields?: Record<string, any>;
}

export interface SearchEmployeesRequest {
  query?: string;
  department?: string;
  title?: string;
  skills?: string[];
  page?: number;
  pageSize?: number;
}

export interface SearchEmployeesResponse {
  employees: Employee[];
  total: number;
  page: number;
  pageSize: number;
  hasMore: boolean;
}

export interface CreateCustomFieldRequest {
  fieldName: string;
  fieldType: 'text' | 'number' | 'date' | 'dropdown' | 'multiselect';
  isRequired?: boolean;
  options?: string[];
  displayOrder?: number;
}

export interface BulkImportRequest {
  employees: CreateEmployeeRequest[];
}

export interface BulkImportResponse {
  created: number;
  updated: number;
  errors: Array<{
    row: number;
    field: string;
    message: string;
  }>;
}

export interface AuditLogQuery {
  startDate?: Date;
  endDate?: Date;
  userId?: string;
  entityType?: string;
  entityId?: string;
  fieldName?: string;
  page?: number;
  pageSize?: number;
}

export interface AnalyticsMetrics {
  totalUsers: number;
  activeUsers30Days: number;
  profileCompleteness: number;
  topSearches: Array<{
    query: string;
    count: number;
  }>;
  mostViewedProfiles: Array<{
    employeeId: string;
    firstName: string;
    lastName: string;
    viewCount: number;
  }>;
  departmentDistribution: Array<{
    department: string;
    count: number;
  }>;
  roleDistribution: Array<{
    title: string;
    count: number;
  }>;
}

// Authentication types
export interface JWTPayload {
  userId: string;
  tenantId: string;
  email: string;
  role: string;
  iat: number;
  exp: number;
}

export interface AuthenticatedUser {
  id: string;
  tenantId: string;
  email: string;
  role: string;
  isActive: boolean;
}

// Error types
export interface ApiError {
  code: string;
  message: string;
  details?: any;
  requestId: string;
}

// Pagination types
export interface PaginationParams {
  page: number;
  pageSize: number;
}

export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  pageSize: number;
  hasMore: boolean;
}

// Tenant configuration types
export interface TenantBranding {
  logoUrl?: string;
  primaryColor?: string;
  accentColor?: string;
}

export interface TenantSettings {
  name: string;
  subdomain: string;
  branding: TenantBranding;
  subscriptionTier: string;
  userLimit: number;
  dataRetentionDays: number;
}

// SCIM types - re-export from dedicated SCIM types file
export * from './scim.types';

// Express Request extensions
declare global {
  namespace Express {
    interface Request {
      id?: string;
      user?: AuthenticatedUser;
      tenant?: Tenant;
      tenantId?: string;
      startTime?: number;
    }
  }
}